apiVersion: v1
kind: Service
metadata:
  name: zitadel-ci-broker
  labels: {{ include "zitadel-ci-broker.labels" . | nindent 4 }}
spec:
  selector: {{ include "zitadel-ci-broker.labels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
